version: '3.7'
services:
  web:
    build:
      context: .
      shm_size: 1G
    ports:
      - 4200:8080
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: eventie
      ENV: dev
